window.SQUADS = {
  England: [
    { n: 1, p: 'GK', nm: 'Jordan Lee Pickford', c: 'Everton' },
    { n: 4, p: 'MF', nm: 'Declan Rice', c: 'Arsenal' },
    { n: 10, p: 'MF', nm: 'Jude Victor William Bellingham', c: 'Real Madrid' },
    { n: 20, p: 'MF', nm: 'Cole Jermaine Palmer', c: 'Chelsea' },
    { n: 14, p: 'DF', nm: 'Trevoh Tom Chalobah', c: 'Crystal Palace' },
    { n: 6, p: 'DF', nm: 'Addji Keaninkin Marc-Israel Guéhi', c: 'Crystal Palace' },
    { n: 24, p: 'DF', nm: 'Reece Lewis James', c: 'Chelsea' },
    { n: 11, p: 'MF', nm: 'Philip Walter Foden', c: 'Manchester City' },
    { n: 18, p: 'MF', nm: 'Elliot Junior Anderson', c: 'Nottingham Forest' },
    { n: 5, p: 'DF', nm: 'Benjamin William White', c: 'Arsenal' },
    { n: 19, p: 'MF', nm: 'Morgan Elliot Rogers', c: 'Aston Villa' },
    { n: 21, p: 'FW', nm: 'Anthony Michael Gordon', c: 'Newcastle United' },
    { n: 15, p: 'DF', nm: 'Ezri Ngoyo Konsa', c: 'Aston Villa' },
    { n: 17, p: 'FW', nm: 'Jarrod Bowen', c: 'West Ham' },
    { n: 3, p: 'DF', nm: 'Harry Jacob Maguire', c: 'Manchester United' },
    { n: 13, p: 'GK', nm: 'Dean Bradley Henderson', c: 'Crystal Palace' },
    { n: 9, p: 'FW', nm: 'Marcus Rashford', c: 'Manchester United' },
    { n: 12, p: 'DF', nm: 'Lewis Kieran Hall', c: 'Newcastle United' },
    { n: 2, p: 'DF', nm: 'Valentino Francisco Livramento', c: 'Newcastle United' },
    { n: 26, p: 'MF', nm: 'Adam James Wharton', c: 'Crystal Palace' },
    { n: 7, p: 'FW', nm: 'Bukayo Ayoyinka Temidayo Moses Saka', c: 'Arsenal' },
    { n: 16, p: 'MF', nm: 'Eberechi Oluchi Eze', c: 'Crystal Palace' },
    { n: 10, p: 'FW', nm: 'Harry Edward Kane', cap: true, c: 'Bayern Munich' },
    { n: 25, p: 'DF', nm: "Nico O'Reilly", c: 'Manchester City' },
    { n: 8, p: 'MF', nm: 'Kobbie Boateng Mainoo', c: 'Manchester United' }
  ],
  Mexico: [
    { n: 1, p: 'GK', nm: 'Guillermo Ochoa', cap: true, c: 'Salernitana' },
    { n: 13, p: 'GK', nm: 'Luis Malagón', c: 'América' },
    { n: 2, p: 'DF', nm: 'Jorge Sánchez', c: 'Porto' },
    { n: 3, p: 'DF', nm: 'César Montes', c: 'Almería' },
    { n: 4, p: 'MF', nm: 'Edson Álvarez', c: 'West Ham' },
    { n: 7, p: 'MF', nm: 'Luis Romo', c: 'Monterrey' },
    { n: 9, p: 'FW', nm: 'Raúl Jiménez', c: 'Fulham' },
    { n: 22, p: 'FW', nm: 'Hirving Lozano', c: 'PSV Eindhoven' }
  ],
  USA: [
    { n: 1, p: 'GK', nm: 'Matt Turner', c: 'Nottingham Forest' },
    { n: 4, p: 'DF', nm: 'Tyler Adams', cap: true, c: 'Bournemouth' },
    { n: 8, p: 'MF', nm: 'Weston McKennie', c: 'Juventus' },
    { n: 10, p: 'FW', nm: 'Christian Pulisic', c: 'AC Milan' },
    { n: 21, p: 'FW', nm: 'Tim Weah', c: 'Juventus' }
  ],
  Canada: [
    { n: 18, p: 'GK', nm: 'Milan Borjan', cap: true, c: 'Slovan Bratislava' },
    { n: 19, p: 'DF', nm: 'Alphonso Davies', c: 'Bayern Munich' },
    { n: 7, p: 'MF', nm: 'Stephen Eustáquio', c: 'Porto' },
    { n: 20, p: 'FW', nm: 'Jonathan David', c: 'Lille' }
  ],
  Brazil: [
    { n: 1, p: 'GK', nm: 'Alisson', c: 'Liverpool' },
    { n: 2, p: 'DF', nm: 'Danilo', cap: true, c: 'Juventus' },
    { n: 4, p: 'DF', nm: 'Marquinhos', c: 'PSG' },
    { n: 5, p: 'MF', nm: 'Casemiro', c: 'Man Utd' },
    { n: 8, p: 'MF', nm: 'Bruno Guimarães', c: 'Newcastle' },
    { n: 7, p: 'FW', nm: 'Vinícius Júnior', c: 'Real Madrid' },
    { n: 9, p: 'FW', nm: 'Richarlison', c: 'Tottenham' },
    { n: 10, p: 'FW', nm: 'Neymar', c: 'Al Hilal' }
  ],
  Sweden: [
    { n: 1, p: 'GK', nm: 'Viktor Johansson', c: 'Stoke City' },
    { n: 23, p: 'GK', nm: 'Bo Kristoffer Nordfeldt', c: 'AIK' },
    { n: 12, p: 'GK', nm: 'Johan Zetterström', c: 'Derby County' },
    { n: 2, p: 'DF', nm: 'Hampus Ekdal', c: 'Burnley' },
    { n: 5, p: 'DF', nm: 'Victor Lindelöf', c: 'Aston Villa' },
    { n: 3, p: 'DF', nm: 'Dennis Svensson', c: 'Borussia Dortmund' },
    { n: 4, p: 'DF', nm: 'Isak Hien', c: 'Atalanta' },
    { n: 6, p: 'DF', nm: 'Gustaf Lagerbielke', c: 'Braga' },
    { n: 22, p: 'DF', nm: 'Gabriel Gudmundsson', c: 'Leeds United' },
    { n: 24, p: 'DF', nm: 'Carl Starfelt', c: 'Celta de Vigo' },
    { n: 13, p: 'DF', nm: 'Emil Holm', c: 'Juventus' },
    { n: 14, p: 'DF', nm: 'Emil Smith', c: 'St. Pauli' },
    { n: 25, p: 'DF', nm: 'Elias Stroud', c: 'Mjällby AIF' },
    { n: 19, p: 'MF', nm: 'Yasin Ayari', c: 'Brighton' },
    { n: 20, p: 'MF', nm: 'Besard Zeneli', c: 'Union St.-Gilloise' },
    { n: 8, p: 'MF', nm: 'Jens Karlström', c: 'Udinese' },
    { n: 16, p: 'MF', nm: 'Mattias Svanberg', c: 'Wolfsburg' },
    { n: 18, p: 'MF', nm: 'Lucas Erik Holger Bergvall', c: 'Tottenham Hotspur' },
    { n: 11, p: 'MF', nm: 'Ken Sema', c: 'Pafos' },
    { n: 17, p: 'FW', nm: 'Viktor Einar Gyökeres', cap: true, c: 'Arsenal' },
    { n: 15, p: 'FW', nm: 'Gustav Nilsson', c: 'Club Brugge' },
    { n: 26, p: 'FW', nm: 'Bjarke Nygren', c: 'Celtic' },
    { n: 7, p: 'FW', nm: 'Anthony David Junior Elanga', c: 'Newcastle United' },
    { n: 9, p: 'FW', nm: 'Alexander Isak', c: 'Liverpool' },
    { n: 21, p: 'FW', nm: 'Anton Bernhardsson', c: 'Holstein Kiel' }
  ],
  France: [
    { n: 16, p: 'GK', nm: 'Mike Peterson Maignan', c: 'AC Milan' },
    { n: 23, p: 'GK', nm: 'Brice Samba', c: 'RC Lens' },
    { n: 1, p: 'GK', nm: 'Robin Risser', c: 'RC Strasbourg' },
    { n: 19, p: 'DF', nm: 'Lucas Digne', c: 'Aston Villa' },
    { n: 2, p: 'DF', nm: 'Malo Arthur Gusto', c: 'Chelsea' },
    { n: 21, p: 'DF', nm: 'Lucas François Bernard Hernandez', c: 'PSG' },
    { n: 22, p: 'DF', nm: 'Théo Bernard François Hernandez', c: 'AC Milan' },
    { n: 24, p: 'DF', nm: 'Ibrahima Konaté', c: 'Liverpool' },
    { n: 5, p: 'DF', nm: 'Jules Olivier Koundé', c: 'Barcelona' },
    { n: 17, p: 'DF', nm: 'William Alain André Gabriel Saliba', c: 'Arsenal' },
    { n: 4, p: 'DF', nm: 'Dayotchanculle Oswald Upamecano', c: 'Bayern Munich' },
    { n: 3, p: 'DF', nm: 'Maxence Guy Lacroix', c: 'Crystal Palace' },
    { n: 13, p: 'MF', nm: 'N\'Golo Kanté', c: 'Al-Ittihad' },
    { n: 6, p: 'MF', nm: 'Emmanuel Manu Koné', c: 'Real Madrid' },
    { n: 14, p: 'MF', nm: 'Adrien Valentin Rabiot', c: 'Marseille' },
    { n: 8, p: 'MF', nm: 'Aurélien Djani Tchouaméni', c: 'Real Madrid' },
    { n: 18, p: 'MF', nm: 'Warren Zaïre-Emery', c: 'PSG' },
    { n: 12, p: 'FW', nm: 'Maghnes Akliouche', c: 'Monaco' },
    { n: 15, p: 'FW', nm: 'Bradley Jean-Manuel Essolisam Addo Barcola', c: 'PSG' },
    { n: 26, p: 'FW', nm: 'Mathis Rayan Cherki', c: 'Manchester City' },
    { n: 7, p: 'FW', nm: 'Masour Ousmane Dembélé', c: 'PSG' },
    { n: 20, p: 'FW', nm: 'Désiré Nonka-Maho Doué', c: 'PSG' },
    { n: 25, p: 'FW', nm: 'Jean-Philippe Mateta', c: 'Crystal Palace' },
    { n: 10, p: 'FW', nm: 'Kylian Mbappé Lottin', cap: true, c: 'Real Madrid' },
    { n: 11, p: 'FW', nm: 'Michael Akpovie Olise', c: 'Bayern Munich' },
    { n: 9, p: 'FW', nm: 'Marcus Lilian Thuram-Ulien', c: 'Inter Milan' }
  ],
  Spain: [
    { n: 23, p: 'GK', nm: 'Unai Simón Mendibil', c: 'Athletic Club' },
    { n: 1, p: 'GK', nm: 'David Raya Martín', c: 'Arsenal' },
    { n: 13, p: 'GK', nm: 'Joan Garcia Pons', c: 'Barcelona' },
    { n: 2, p: 'DF', nm: 'Pau Cubarsí Paredes', c: 'Barcelona' },
    { n: 24, p: 'DF', nm: 'Marc Cucurella Saseta', c: 'Chelsea' },
    { n: 23, p: 'DF', nm: 'Pedro Antonio Porro Sauceda', c: 'Tottenham Hotspur' },
    { n: 3, p: 'DF', nm: 'Dean Donny Huijsen Wijsmuller', c: 'Real Madrid' },
    { n: 12, p: 'DF', nm: 'Álvaro Fernández Carreras', c: 'Benfica' },
    { n: 16, p: 'MF', nm: 'Rodrigo Hernández Cascante', cap: true, c: 'Manchester City' },
    { n: 20, p: 'MF', nm: 'Pedro González López', c: 'Barcelona' },
    { n: 10, p: 'MF', nm: 'Daniel Olmo Carvajal', c: 'Barcelona' },
    { n: 16, p: 'MF', nm: 'Fermín López Marín', c: 'Barcelona' },
    { n: 21, p: 'MF', nm: 'Mikel Oyarzabal Ugarte', c: 'Real Sociedad' },
    { n: 19, p: 'FW', nm: 'Lamine Yamal Nasraoui Ebana', c: 'Barcelona' },
    { n: 11, p: 'FW', nm: 'Ferran Torres García', c: 'Barcelona' },
    { n: 7, p: 'FW', nm: 'Ander Barrenetxea Muguruza', c: 'Real Sociedad' },
    { n: 21, p: 'FW', nm: 'Mikel Oyarzabal Ugarte', c: 'Real Sociedad' },
    { n: 14, p: 'FW', nm: 'Víctor Muñoz Villanueva', c: 'Osasuna' }
  ],
  Belgium: [
    { n: 1, p: 'GK', nm: 'Mats Sels', c: 'Nottingham Forest' },
    { n: 2, p: 'GK', nm: 'Thibaut Courtois', c: 'Real Madrid' },
    { n: 3, p: 'GK', nm: 'Senne Lammens', c: 'Royal Antwerp' },
    { n: 4, p: 'DF', nm: 'Arthur Theate', c: 'Eintracht Frankfurt' },
    { n: 5, p: 'DF', nm: 'Brandon Mechele', c: 'Club Brugge' },
    { n: 6, p: 'DF', nm: 'Nathan Ngoy', c: 'Juventus' },
    { n: 7, p: 'DF', nm: 'Koni De Winter', c: 'Genk' },
    { n: 8, p: 'DF', nm: 'Zeno Debast', c: 'Sporting CP' },
    { n: 9, p: 'DF', nm: 'Maxim De Cuyper', c: 'Club Brugge' },
    { n: 10, p: 'DF', nm: 'Joaquin Seys', c: 'Club Brugge' },
    { n: 11, p: 'DF', nm: 'Thomas Meunier', c: 'Club Brugge' },
    { n: 12, p: 'DF', nm: 'Timothy Castagne', c: 'Fulham' },
    { n: 13, p: 'MF', nm: 'Nicolas Raskin', c: 'Rangers' },
    { n: 14, p: 'MF', nm: 'Axel Witsel', c: 'Sporting CP' },
    { n: 15, p: 'MF', nm: 'Hans Vanaken', c: 'Club Brugge' },
    { n: 16, p: 'MF', nm: 'Kevin De Bruyne', cap: true, c: 'Manchester City' },
    { n: 17, p: 'MF', nm: 'Youri Tielemans', c: 'Aston Villa' },
    { n: 18, p: 'MF', nm: 'Amadou Onana', c: 'Aston Villa' },
    { n: 19, p: 'FW', nm: 'Jeremy Doku', c: 'Manchester City' },
    { n: 20, p: 'FW', nm: 'Alexis Saelemaekers', c: 'AC Milan' },
    { n: 21, p: 'FW', nm: 'Matthias Fernandez Pardo', c: 'Anderlecht' },
    { n: 22, p: 'FW', nm: 'Lucas Stassin', c: 'Real Sociedad' },
    { n: 23, p: 'FW', nm: 'Romelu Lukaku', c: 'Napoli' },
    { n: 24, p: 'FW', nm: 'Leandro Trossard', c: 'Arsenal' },
    { n: 25, p: 'FW', nm: 'Charles De Ketelaere', c: 'Atalanta' },
    { n: 26, p: 'FW', nm: 'Dodi Lukebakio', c: 'Sevilla' }
  ]
};
