window.SQUADS = {
  England: [
    { n: 1, p: 'GK', nm: 'Jordan Pickford', c: 'Everton' },
    { n: 12, p: 'GK', nm: 'Dean Henderson', c: 'Crystal Palace' },
    { n: 23, p: 'GK', nm: 'James Trafford', c: 'Manchester City' },
    { n: 2, p: 'DF', nm: 'Reece James', c: 'Chelsea' },
    { n: 3, p: 'DF', nm: 'Tino Livramento', c: 'Newcastle United' },
    { n: 4, p: 'DF', nm: 'Marc Guehi', c: 'Manchester City' },
    { n: 5, p: 'DF', nm: 'Ezri Konsa', c: 'Aston Villa' },
    { n: 6, p: 'DF', nm: 'John Stones', c: 'Manchester City' },
    { n: 13, p: 'DF', nm: 'Jarell Quansah', c: 'Bayer Leverkusen' },
    { n: 14, p: 'DF', nm: "Nico O'Reilly", c: 'Manchester City' },
    { n: 15, p: 'DF', nm: 'Dan Burn', c: 'Newcastle United' },
    { n: 22, p: 'DF', nm: 'Djed Spence', c: 'Tottenham Hotspur' },
    { n: 8, p: 'MF', nm: 'Declan Rice', c: 'Arsenal' },
    { n: 16, p: 'MF', nm: 'Elliot Anderson', c: 'Nottingham Forest' },
    { n: 10, p: 'MF', nm: 'Jude Bellingham', c: 'Real Madrid' },
    { n: 17, p: 'MF', nm: 'Jordan Henderson', c: 'Brentford' },
    { n: 18, p: 'MF', nm: 'Morgan Rogers', c: 'Aston Villa' },
    { n: 19, p: 'MF', nm: 'Kobbie Mainoo', c: 'Manchester United' },
    { n: 9, p: 'FW', nm: 'Harry Kane', cap: true, c: 'Bayern Munich' },
    { n: 11, p: 'FW', nm: 'Ivan Toney', c: 'Al-Ahli FC' },
    { n: 20, p: 'FW', nm: 'Ollie Watkins', c: 'Aston Villa' },
    { n: 7, p: 'FW', nm: 'Bukayo Saka', c: 'Arsenal' },
    { n: 21, p: 'FW', nm: 'Noni Madueke', c: 'Arsenal' },
    { n: 24, p: 'FW', nm: 'Marcus Rashford', c: 'Barcelona' },
    { n: 25, p: 'FW', nm: 'Anthony Gordon', c: 'Newcastle United' },
    { n: 26, p: 'FW', nm: 'Eberechi Eze', c: 'Arsenal' }
  ],
  Mexico: [
    { n: 1, p: 'GK', nm: 'Guillermo Ochoa', cap: true, c: 'Salernitana' },
    { n: 13, p: 'GK', nm: 'Luis Malagón', c: 'América' },
    { n: 2, p: 'DF', nm: 'Jorge Sánchez', c: 'Porto' },
    { n: 3, p: 'DF', nm: 'César Montes', c: 'Almería' },
    { n: 4, p: 'MF', nm: 'Edson Álvarez', c: 'West Ham' },
    { n: 7, p: 'MF', nm: 'Luis Romo', c: 'Monterrey' },
    { n: 9, p: 'FW', nm: 'Raúl Jiménez', c: 'Fulham' },
    { n: 22, p: 'FW', nm: 'Hirving Lozano', c: 'PSV Eindhoven' }
  ],
  USA: [
    { n: 1, p: 'GK', nm: 'Matt Turner', c: 'Nottingham Forest' },
    { n: 4, p: 'DF', nm: 'Tyler Adams', cap: true, c: 'Bournemouth' },
    { n: 8, p: 'MF', nm: 'Weston McKennie', c: 'Juventus' },
    { n: 10, p: 'FW', nm: 'Christian Pulisic', c: 'AC Milan' },
    { n: 21, p: 'FW', nm: 'Tim Weah', c: 'Juventus' }
  ],
  Canada: [
    { n: 18, p: 'GK', nm: 'Milan Borjan', cap: true, c: 'Slovan Bratislava' },
    { n: 19, p: 'DF', nm: 'Alphonso Davies', c: 'Bayern Munich' },
    { n: 7, p: 'MF', nm: 'Stephen Eustáquio', c: 'Porto' },
    { n: 20, p: 'FW', nm: 'Jonathan David', c: 'Lille' }
  ],
  Brazil: [
    { n: 1, p: 'GK', nm: 'Alisson', c: 'Liverpool' },
    { n: 23, p: 'GK', nm: 'Ederson', c: 'Fenerbahçe' },
    { n: 12, p: 'GK', nm: 'Weverton', c: 'Grêmio' },
    { n: 6, p: 'DF', nm: 'Alex Sandro', c: 'Flamengo' },
    { n: 3, p: 'DF', nm: 'Gleison Bremer', c: 'Juventus' },
    { n: 2, p: 'DF', nm: 'Danilo', cap: true, c: 'Flamengo' },
    { n: 13, p: 'DF', nm: 'Douglas Santos', c: 'Zenit St. Petersburg' },
    { n: 5, p: 'DF', nm: 'Gabriel Magalhães', c: 'Arsenal' },
    { n: 24, p: 'DF', nm: 'Roger Ibañez', c: 'Al-Ahli' },
    { n: 22, p: 'DF', nm: 'Léo Pereira', c: 'Flamengo' },
    { n: 4, p: 'DF', nm: 'Marquinhos', c: 'PSG' },
    { n: 25, p: 'DF', nm: 'Wesley Vinícius França Lima', c: 'AS Roma' },
    { n: 8, p: 'MF', nm: 'Carlos Henrique Casemiro', c: 'Manchester United' },
    { n: 17, p: 'MF', nm: 'Bruno Guimarães', c: 'Newcastle United' },
    { n: 15, p: 'MF', nm: 'Fabinho', c: 'Al-Ittihad' },
    { n: 16, p: 'MF', nm: 'Lucas Paquetá', c: 'Flamengo' },
    { n: 19, p: 'MF', nm: 'Danilo Santos', c: 'Botafogo' },
    { n: 9, p: 'FW', nm: 'Endrick Felipe Moreira de Sousa', c: 'Lyon' },
    { n: 11, p: 'FW', nm: 'Gabriel Martinelli', c: 'Arsenal' },
    { n: 21, p: 'FW', nm: 'Igor Thiago', c: 'Brentford' },
    { n: 20, p: 'FW', nm: 'Luiz Henrique', c: 'Zenit' },
    { n: 18, p: 'FW', nm: 'Matheus Cunha', c: 'Manchester United' },
    { n: 10, p: 'FW', nm: 'Neymar Jr', c: 'Santos' },
    { n: 7, p: 'FW', nm: 'Raphinha Dias Belloli', c: 'Barcelona' },
    { n: 14, p: 'FW', nm: 'Vinícius Júnior', c: 'Real Madrid' },
    { n: 26, p: 'FW', nm: 'Rayan Vitor Simplício Rocha', c: 'Bournemouth' }
  ],
  Sweden: [
    { n: 1, p: 'GK', nm: 'Jacob Widell Zetterström', c: 'Derby County' },
    { n: 12, p: 'GK', nm: 'Viktor Johansson', c: 'Stoke City' },
    { n: 23, p: 'GK', nm: 'Kristoffer Nordfeldt', c: 'AIK' },
    { n: 2, p: 'DF', nm: 'Gustaf Lagerbielke', c: 'Braga' },
    { n: 3, p: 'DF', nm: 'Victor Nilsson Lindelöf', c: 'Aston Villa' },
    { n: 4, p: 'DF', nm: 'Isak Hien', c: 'Atalanta' },
    { n: 5, p: 'DF', nm: 'Gabriel Gudmundsson', c: 'Leeds United' },
    { n: 6, p: 'DF', nm: 'Emil Holm', c: 'Juventus' },
    { n: 8, p: 'DF', nm: 'Daniel Svensson', c: 'Borussia Dortmund' },
    { n: 14, p: 'DF', nm: 'Hjalmar Ekdal', c: 'Burnley' },
    { n: 15, p: 'DF', nm: 'Carl Starfelt', c: 'Celta de Vigo' },
    { n: 20, p: 'DF', nm: 'Eric Smith', c: 'St. Pauli' },
    { n: 24, p: 'DF', nm: 'Elliot Stroud', c: 'Mjällby AIF' },
    { n: 7, p: 'MF', nm: 'Lucas Bergvall', c: 'Tottenham Hotspur' },
    { n: 13, p: 'MF', nm: 'Ken Sema', c: 'Pafos' },
    { n: 16, p: 'MF', nm: 'Jesper Karlström', c: 'Udinese' },
    { n: 18, p: 'MF', nm: 'Yasin Ayari', c: 'Brighton' },
    { n: 19, p: 'MF', nm: 'Mattias Svanberg', c: 'Wolfsburg' },
    { n: 22, p: 'MF', nm: 'Besfort Zeneli', c: 'Union St.-Gilloise' },
    { n: 9, p: 'FW', nm: 'Alexander Isak', c: 'Liverpool' },
    { n: 10, p: 'FW', nm: 'Benjamin Nygren', c: 'Celtic' },
    { n: 11, p: 'FW', nm: 'Anthony Elanga', c: 'Newcastle United' },
    { n: 17, p: 'FW', nm: 'Viktor Gyökeres', cap: true, c: 'Arsenal' },
    { n: 21, p: 'FW', nm: 'Alexander Bernhardsson', c: 'Holstein Kiel' },
    { n: 25, p: 'FW', nm: 'Gustaf Nilsson', c: 'Club Brugge' },
    { n: 26, p: 'FW', nm: 'Taha Ali', c: 'IFK Norrköping' }
  ],
  France: [
    { n: 16, p: 'GK', nm: 'Mike Peterson Maignan', c: 'AC Milan' },
    { n: 23, p: 'GK', nm: 'Brice Samba', c: 'RC Lens' },
    { n: 1, p: 'GK', nm: 'Robin Risser', c: 'RC Strasbourg' },
    { n: 19, p: 'DF', nm: 'Lucas Digne', c: 'Aston Villa' },
    { n: 2, p: 'DF', nm: 'Malo Arthur Gusto', c: 'Chelsea' },
    { n: 21, p: 'DF', nm: 'Lucas François Bernard Hernandez', c: 'PSG' },
    { n: 22, p: 'DF', nm: 'Théo Bernard François Hernandez', c: 'AC Milan' },
    { n: 24, p: 'DF', nm: 'Ibrahima Konaté', c: 'Liverpool' },
    { n: 5, p: 'DF', nm: 'Jules Olivier Koundé', c: 'Barcelona' },
    { n: 17, p: 'DF', nm: 'William Alain André Gabriel Saliba', c: 'Arsenal' },
    { n: 4, p: 'DF', nm: 'Dayotchanculle Oswald Upamecano', c: 'Bayern Munich' },
    { n: 3, p: 'DF', nm: 'Maxence Guy Lacroix', c: 'Crystal Palace' },
    { n: 13, p: 'MF', nm: 'N\'Golo Kanté', c: 'Al-Ittihad' },
    { n: 6, p: 'MF', nm: 'Emmanuel Manu Koné', c: 'Real Madrid' },
    { n: 14, p: 'MF', nm: 'Adrien Valentin Rabiot', c: 'Marseille' },
    { n: 8, p: 'MF', nm: 'Aurélien Djani Tchouaméni', c: 'Real Madrid' },
    { n: 18, p: 'MF', nm: 'Warren Zaïre-Emery', c: 'PSG' },
    { n: 12, p: 'FW', nm: 'Maghnes Akliouche', c: 'Monaco' },
    { n: 15, p: 'FW', nm: 'Bradley Jean-Manuel Essolisam Addo Barcola', c: 'PSG' },
    { n: 26, p: 'FW', nm: 'Mathis Rayan Cherki', c: 'Manchester City' },
    { n: 7, p: 'FW', nm: 'Masour Ousmane Dembélé', c: 'PSG' },
    { n: 20, p: 'FW', nm: 'Désiré Nonka-Maho Doué', c: 'PSG' },
    { n: 25, p: 'FW', nm: 'Jean-Philippe Mateta', c: 'Crystal Palace' },
    { n: 10, p: 'FW', nm: 'Kylian Mbappé Lottin', cap: true, c: 'Real Madrid' },
    { n: 11, p: 'FW', nm: 'Michael Akpovie Olise', c: 'Bayern Munich' },
    { n: 9, p: 'FW', nm: 'Marcus Lilian Thuram-Ulien', c: 'Inter Milan' }
  ],
  Spain: [
    { n: 23, p: 'GK', nm: 'Unai Simón Mendibil', c: 'Athletic Club' },
    { n: 1, p: 'GK', nm: 'David Raya Martín', c: 'Arsenal' },
    { n: 13, p: 'GK', nm: 'Joan Garcia Pons', c: 'Barcelona' },
    { n: 2, p: 'DF', nm: 'Pau Cubarsí Paredes', c: 'Barcelona' },
    { n: 24, p: 'DF', nm: 'Marc Cucurella Saseta', c: 'Chelsea' },
    { n: 23, p: 'DF', nm: 'Pedro Antonio Porro Sauceda', c: 'Tottenham Hotspur' },
    { n: 3, p: 'DF', nm: 'Dean Donny Huijsen Wijsmuller', c: 'Real Madrid' },
    { n: 12, p: 'DF', nm: 'Álvaro Fernández Carreras', c: 'Benfica' },
    { n: 16, p: 'MF', nm: 'Rodrigo Hernández Cascante', cap: true, c: 'Manchester City' },
    { n: 20, p: 'MF', nm: 'Pedro González López', c: 'Barcelona' },
    { n: 10, p: 'MF', nm: 'Daniel Olmo Carvajal', c: 'Barcelona' },
    { n: 16, p: 'MF', nm: 'Fermín López Marín', c: 'Barcelona' },
    { n: 21, p: 'MF', nm: 'Mikel Oyarzabal Ugarte', c: 'Real Sociedad' },
    { n: 19, p: 'FW', nm: 'Lamine Yamal Nasraoui Ebana', c: 'Barcelona' },
    { n: 11, p: 'FW', nm: 'Ferran Torres García', c: 'Barcelona' },
    { n: 7, p: 'FW', nm: 'Ander Barrenetxea Muguruza', c: 'Real Sociedad' },
    { n: 21, p: 'FW', nm: 'Mikel Oyarzabal Ugarte', c: 'Real Sociedad' },
    { n: 14, p: 'FW', nm: 'Víctor Muñoz Villanueva', c: 'Osasuna' }
  ],
  Belgium: [
    { n: 1, p: 'GK', nm: 'Mike Penders', c: 'KRC Genk' },
    { n: 2, p: 'GK', nm: 'Thibaut Courtois', c: 'Real Madrid' },
    { n: 3, p: 'GK', nm: 'Senne Lammens', c: 'Royal Antwerp' },
    { n: 4, p: 'DF', nm: 'Arthur Theate', c: 'Eintracht Frankfurt' },
    { n: 5, p: 'DF', nm: 'Brandon Mechele', c: 'Club Brugge' },
    { n: 6, p: 'DF', nm: 'Nathan Ngoy', c: 'Juventus' },
    { n: 7, p: 'DF', nm: 'Koni De Winter', c: 'Genk' },
    { n: 8, p: 'DF', nm: 'Zeno Debast', c: 'Sporting CP' },
    { n: 9, p: 'DF', nm: 'Maxim De Cuyper', c: 'Club Brugge' },
    { n: 10, p: 'DF', nm: 'Joaquin Seys', c: 'Club Brugge' },
    { n: 11, p: 'DF', nm: 'Thomas Meunier', c: 'Club Brugge' },
    { n: 12, p: 'DF', nm: 'Timothy Castagne', c: 'Fulham' },
    { n: 13, p: 'MF', nm: 'Nicolas Raskin', c: 'Rangers' },
    { n: 14, p: 'MF', nm: 'Axel Witsel', c: 'Sporting CP' },
    { n: 15, p: 'MF', nm: 'Hans Vanaken', c: 'Club Brugge' },
    { n: 16, p: 'MF', nm: 'Kevin De Bruyne', cap: true, c: 'Manchester City' },
    { n: 17, p: 'MF', nm: 'Youri Tielemans', c: 'Aston Villa' },
    { n: 18, p: 'MF', nm: 'Amadou Onana', c: 'Aston Villa' },
    { n: 19, p: 'FW', nm: 'Jeremy Doku', c: 'Manchester City' },
    { n: 20, p: 'FW', nm: 'Alexis Saelemaekers', c: 'AC Milan' },
    { n: 21, p: 'FW', nm: 'Matias Fernandez-Pardo', c: 'Anderlecht' },
    { n: 22, p: 'FW', nm: 'Diego Moreira', c: 'AS Monaco' },
    { n: 23, p: 'FW', nm: 'Romelu Lukaku', c: 'Napoli' },
    { n: 24, p: 'FW', nm: 'Leandro Trossard', c: 'Arsenal' },
    { n: 25, p: 'FW', nm: 'Charles De Ketelaere', c: 'Atalanta' },
    { n: 26, p: 'FW', nm: 'Dodi Lukebakio', c: 'Sevilla' }
  ],
  'New Zealand': [
    { n: 1, p: 'GK', nm: 'Max Crocombe', c: 'Almería' },
    { n: 23, p: 'GK', nm: 'Alex Paulsen', c: 'Wellington Phoenix' },
    { n: 12, p: 'GK', nm: 'Michael Woud', c: 'Northampton Town' },
    { n: 2, p: 'DF', nm: 'Tyler Bindon', c: 'Minnesota United' },
    { n: 5, p: 'DF', nm: 'Michael Boxall', c: 'Minnesota United' },
    { n: 3, p: 'DF', nm: 'Liberato Cacace', c: 'Empoli' },
    { n: 4, p: 'DF', nm: 'Francis De Vries', c: 'Wellington Phoenix' },
    { n: 6, p: 'DF', nm: 'Callan Elliot', c: 'Wellington Phoenix' },
    { n: 22, p: 'DF', nm: 'Tim Payne', c: 'Auckland FC' },
    { n: 15, p: 'DF', nm: 'Nando Pijnaker', c: 'Go Ahead Eagles' },
    { n: 13, p: 'DF', nm: 'Tommy Smith', c: 'Colorado Rapids' },
    { n: 24, p: 'DF', nm: 'Finn Surman', c: 'Wellington Phoenix' },
    { n: 8, p: 'MF', nm: 'Lachlan Bayliss', c: 'Wellington Phoenix' },
    { n: 14, p: 'MF', nm: 'Joe Bell', c: 'Norwich City' },
    { n: 11, p: 'MF', nm: 'Alex Rufer', c: 'Wolfsburg' },
    { n: 7, p: 'MF', nm: 'Marko Stamenić', c: 'Club Brugge' },
    { n: 16, p: 'MF', nm: 'Ryan Thomas', c: 'PEC Zwolle' },
    { n: 17, p: 'FW', nm: 'Kosta Barbarouses', c: 'Vancouver Whitecaps' },
    { n: 19, p: 'FW', nm: 'Matt Garbett', c: 'Auckland FC' },
    { n: 20, p: 'FW', nm: 'Eli Just', c: 'Wellington Phoenix' },
    { n: 21, p: 'FW', nm: 'Callum McCowatt', c: 'Heracles Almelo' },
    { n: 18, p: 'FW', nm: 'Ben Old', c: 'Vitesse' },
    { n: 25, p: 'FW', nm: 'Jesse Randall', c: 'Auckland FC' },
    { n: 10, p: 'FW', nm: 'Sarpreet Singh', c: 'NEC Nijmegen' },
    { n: 26, p: 'FW', nm: 'Ben Waine', c: 'Vitesse' },
    { n: 9, p: 'FW', nm: 'Chris Wood', cap: true, c: 'Nottingham Forest' }
  ],
  'Bosnia-Herzegovina': [
    { n: 1, p: 'GK', nm: 'Nikola Vasilj', c: 'FC St. Pauli' },
    { n: 23, p: 'GK', nm: 'Martin Zlomislić', c: 'HNK Rijeka' },
    { n: 12, p: 'GK', nm: 'Osman Hadžikić', c: 'NK Slaven Belupo' },
    { n: 3, p: 'DF', nm: 'Sead Kolašinac', c: 'Atalanta' },
    { n: 5, p: 'DF', nm: 'Dennis Hadžikadunić', c: 'US Sampdoria' },
    { n: 2, p: 'DF', nm: 'Amar Dedić', c: 'SL Benfica' },
    { n: 4, p: 'DF', nm: 'Nikola Katić', c: 'FC Schalke 04' },
    { n: 6, p: 'DF', nm: 'Tarik Muharemović', c: 'US Sassuolo' },
    { n: 22, p: 'DF', nm: 'Nihad Mujakić', c: 'Gaziantep FK' },
    { n: 15, p: 'DF', nm: 'Stjepan Radeljić', c: 'HNK Rijeka' },
    { n: 24, p: 'DF', nm: 'Nidal Celik', c: 'RC Lens' },
    { n: 8, p: 'MF', nm: 'Amir Hadžiahmetović', c: 'Hull City' },
    { n: 18, p: 'MF', nm: 'Benjamin Tahirović', c: 'Brøndby IF' },
    { n: 14, p: 'MF', nm: 'Dzenis Burnić', c: 'Karlsruher SC' },
    { n: 16, p: 'MF', nm: 'Armin Gigović', c: 'BSC Young Boys' },
    { n: 13, p: 'MF', nm: 'Ivan Bašić', c: 'FC Astana' },
    { n: 17, p: 'MF', nm: 'Amar Memić', c: 'Viktoria Plzeň' },
    { n: 19, p: 'MF', nm: 'Ivan Šunjić', c: 'Pafos FC' },
    { n: 20, p: 'MF', nm: 'Ermin Mahmić', c: 'Slovan Liberec' },
    { n: 9, p: 'FW', nm: 'Edin Džeko', cap: true, c: 'FC Schalke 04' },
    { n: 11, p: 'FW', nm: 'Ermedin Demirović', c: 'VfB Stuttgart' },
    { n: 7, p: 'FW', nm: 'Samed Baždar', c: 'Jagiellonia Białystok' },
    { n: 21, p: 'FW', nm: 'Kerim Alajbegović', c: 'Red Bull Salzburg' },
    { n: 10, p: 'FW', nm: 'Esmir Bajraktarević', c: 'PSV Eindhoven' },
    { n: 25, p: 'FW', nm: 'Haris Tabaković', c: 'Borussia Mönchengladbach' },
    { n: 26, p: 'FW', nm: 'Jovo Lukić', c: 'FC Universitatea Cluj' }
  ],
  Japan: [
    { n: 1, p: 'GK', nm: 'Zion Suzuki', c: 'Parma Calcio 1913' },
    { n: 12, p: 'GK', nm: 'Keisuke Osako', c: 'Sanfrecce Hiroshima' },
    { n: 23, p: 'GK', nm: 'Tomoki Hayakawa', c: 'Kashima Antlers' },
    { n: 5, p: 'DF', nm: 'Hiroki Ito', c: 'Bayern Munich' },
    { n: 3, p: 'DF', nm: 'Ko Itakura', c: 'AFC Ajax' },
    { n: 22, p: 'DF', nm: 'Takehiro Tomiyasu', c: 'AFC Ajax' },
    { n: 4, p: 'DF', nm: 'Tsuyoshi Watanabe', c: 'Feyenoord' },
    { n: 2, p: 'DF', nm: 'Yukinari Sugawara', c: 'Werder Bremen' },
    { n: 15, p: 'DF', nm: 'Shogo Taniguchi', c: 'Sint-Truidense VV' },
    { n: 16, p: 'DF', nm: 'Ayumu Seko', c: 'Le Havre AC' },
    { n: 24, p: 'DF', nm: 'Junnosuke Suzuki', c: 'FC Copenhagen' },
    { n: 13, p: 'DF', nm: 'Yuto Nagatomo', c: 'FC Tokyo' },
    { n: 17, p: 'MF', nm: 'Wataru Endo', cap: true, c: 'Liverpool' },
    { n: 8, p: 'MF', nm: 'Kaishu Sano', c: '1. FSV Mainz 05' },
    { n: 10, p: 'MF', nm: 'Daichi Kamada', c: 'Crystal Palace' },
    { n: 6, p: 'MF', nm: 'Ao Tanaka', c: 'Leeds United' },
    { n: 11, p: 'MF', nm: 'Junya Ito', c: 'KRC Genk' },
    { n: 14, p: 'FW', nm: 'Takefusa Kubo', c: 'Real Sociedad' },
    { n: 7, p: 'FW', nm: 'Ritsu Doan', c: 'Eintracht Frankfurt' },
    { n: 19, p: 'FW', nm: 'Keito Nakamura', c: 'Stade de Reims' },
    { n: 9, p: 'FW', nm: 'Daizen Maeda', c: 'Celtic' },
    { n: 20, p: 'FW', nm: 'Ayase Ueda', c: 'Feyenoord' },
    { n: 21, p: 'FW', nm: 'Koki Ogawa', c: 'NEC Nijmegen' },
    { n: 25, p: 'FW', nm: 'Keisuke Goto', c: 'Sint-Truidense VV' },
    { n: 26, p: 'FW', nm: 'Kento Shiogai', c: 'VfL Wolfsburg' },
    { n: 18, p: 'FW', nm: 'Yuito Suzuki', c: 'SC Freiburg' }
  ],
  'Ivory Coast': [
    { n: 1, p: 'GK', nm: 'Yahia Fofana', c: 'Çaykur Rizespor' },
    { n: 16, p: 'GK', nm: 'Mohamed Koné', c: 'Charleroi' },
    { n: 23, p: 'GK', nm: 'Alban-Marc Lafont', c: 'Panathinaikos' },
    { n: 5, p: 'DF', nm: 'Badobre Emmanuel Elysee Djedje Agbadou', c: 'Beşiktaş' },
    { n: 2, p: 'DF', nm: 'Clément Akpa', c: 'Auxerre' },
    { n: 6, p: 'DF', nm: 'Ousmane Diomandé', c: 'Sporting CP' },
    { n: 3, p: 'DF', nm: 'Guéla Maho Lewis Doué', c: 'Strasbourg' },
    { n: 12, p: 'DF', nm: 'Ghislain Konan', c: 'Gil Vicente' },
    { n: 4, p: 'DF', nm: 'Kouakou Odilon Dorgeless Kossounou', c: 'Atalanta' },
    { n: 13, p: 'DF', nm: 'Evan Ndicka', c: 'AS Roma' },
    { n: 22, p: 'DF', nm: 'Wilfried Stephane Singo', c: 'Galatasaray' },
    { n: 8, p: 'MF', nm: 'Seko Fofana', cap: true, c: 'FC Porto' },
    { n: 14, p: 'MF', nm: 'Parfait Guiagon', c: 'Charleroi' },
    { n: 7, p: 'MF', nm: 'Christ Ravynel Inao Oulaï', c: 'Trabzonspor' },
    { n: 10, p: 'MF', nm: 'Franck Kessié', c: 'Al-Ahli' },
    { n: 17, p: 'MF', nm: 'Ibrahim Sangaré', c: 'Nottingham Forest' },
    { n: 11, p: 'MF', nm: 'Jean-Mickaël Seri', c: 'Maribor' },
    { n: 19, p: 'FW', nm: 'Simon Adingra', c: 'AS Monaco' },
    { n: 20, p: 'FW', nm: 'Ange-Yoan Bonny', c: 'Inter Milan' },
    { n: 18, p: 'FW', nm: 'Amad Diallo', c: 'Manchester United' },
    { n: 15, p: 'FW', nm: 'Oumar Diakité', c: 'Cercle Brugge' },
    { n: 24, p: 'FW', nm: 'Yan Diomandé', c: 'RB Leipzig' },
    { n: 21, p: 'FW', nm: 'Evann Ludovic Vidjannagni Guessand', c: 'Aston Villa' },
    { n: 9, p: 'FW', nm: 'Nicolas Pépé', c: 'Villarreal' },
    { n: 25, p: 'FW', nm: 'Bazoumana Touré', c: 'TSG Hoffenheim' },
    { n: 26, p: 'FW', nm: 'Sepe Elye Delmas Wahi', c: 'OGC Nice' }
  ],
  Tunisia: [
    { n: 1, p: 'GK', nm: 'Aymen Dahmen', c: 'CS Sfax' },
    { n: 16, p: 'GK', nm: 'Sabri Ben Hassen', c: 'ES Sahel' },
    { n: 23, p: 'GK', nm: 'Abdelmouhib Chamakh', c: 'Club Africain' },
    { n: 2, p: 'DF', nm: 'Yan Valéry', c: 'BSC Young Boys' },
    { n: 3, p: 'DF', nm: 'Moutaz Neffati', c: 'IFK Norrköping' },
    { n: 5, p: 'DF', nm: 'Dylan Bronn', c: 'Servette FC' },
    { n: 22, p: 'DF', nm: 'Raed Chikhaoui', c: 'US Monastir' },
    { n: 4, p: 'DF', nm: 'Montassar Talbi', c: 'FC Lorient' },
    { n: 15, p: 'DF', nm: 'Adem Arous', c: 'Kasımpaşa' },
    { n: 6, p: 'DF', nm: 'Omar Rekik', c: 'NK Maribor' },
    { n: 13, p: 'DF', nm: 'Ali Abdi', c: 'OGC Nice' },
    { n: 24, p: 'DF', nm: 'Mohamed Ben Hmida', c: 'ES Tunis' },
    { n: 8, p: 'MF', nm: 'Ellyes Skhiri', cap: true, c: 'Eintracht Frankfurt' },
    { n: 14, p: 'MF', nm: 'Anis Ben Slimane', c: 'Norwich City' },
    { n: 19, p: 'MF', nm: 'Rani Khedira', c: 'Union Berlin' },
    { n: 17, p: 'MF', nm: 'Mortadha Ben Ouanes', c: 'Kasımpaşa' },
    { n: 20, p: 'MF', nm: 'Ismaël Gharbi', c: 'FC Augsburg' },
    { n: 18, p: 'MF', nm: 'Mohamed Hadj-Mahmoud', c: 'FC Lugano' },
    { n: 7, p: 'MF', nm: 'Hannibal Mejbri', c: 'Burnley' },
    { n: 9, p: 'FW', nm: 'Elias Saâd', c: 'Hannover 96' },
    { n: 10, p: 'FW', nm: 'Khalil Ayari', c: 'PSG' },
    { n: 11, p: 'FW', nm: 'Elias Achouri', c: 'FC Copenhagen' },
    { n: 21, p: 'FW', nm: 'Sebastian Tounekti', c: 'Celtic' },
    { n: 25, p: 'FW', nm: 'Hazem Mastouri', c: 'Dynamo Moscow' },
    { n: 26, p: 'FW', nm: 'Firas Chawat', c: 'Club Africain' },
    { n: 12, p: 'FW', nm: 'Rayan Elloumi', c: 'Vancouver Whitecaps' }
  ],
  Haiti: [
    { n: 1, p: 'GK', nm: 'Alexandre Pierre', c: 'FC Sochaux' },
    { n: 23, p: 'GK', nm: 'Johny Placide', c: 'SC Bastia' },
    { n: 12, p: 'GK', nm: 'Josué Duverger', c: 'Cosmos Koblenz' },
    { n: 6, p: 'DF', nm: 'Ricardo Adé', c: 'LDU Quito' },
    { n: 2, p: 'DF', nm: 'Carlens Arcus', c: 'Angers SCO' },
    { n: 3, p: 'DF', nm: 'Wilguens Paugain', c: 'SV Zulte Waregem' },
    { n: 4, p: 'DF', nm: 'Martin Expérience', c: 'AS Nancy-Lorraine' },
    { n: 15, p: 'DF', nm: 'Duke Lacroix', c: 'Colorado Springs Switchbacks' },
    { n: 22, p: 'DF', nm: 'Hannes Delcroix', c: 'FC Lugano' },
    { n: 5, p: 'DF', nm: 'Jean-Kevin Duverne', c: 'KAA Gent' },
    { n: 24, p: 'DF', nm: 'Keeto Thermoncy', c: 'BSC Young Boys' },
    { n: 17, p: 'MF', nm: 'Jean-Ricner Bellegarde', cap: true, c: 'Wolverhampton Wanderers' },
    { n: 14, p: 'MF', nm: 'Jean-Jacques Danley', c: 'Philadelphia Union' },
    { n: 18, p: 'MF', nm: 'Dominique Simon', c: 'FC Tatran Prešov' },
    { n: 8, p: 'MF', nm: 'Leverton Pierre', c: 'FC Vizela' },
    { n: 13, p: 'MF', nm: 'Woodenski Pierre', c: 'Violette AC' },
    { n: 16, p: 'MF', nm: 'Carl Sainté', c: 'El Paso Locomotive FC' },
    { n: 10, p: 'FW', nm: 'Wilson Isidor', c: 'Sunderland AFC' },
    { n: 19, p: 'FW', nm: 'Derrick Etienne', c: 'Toronto FC' },
    { n: 9, p: 'FW', nm: 'Don Deedson Louicius', c: 'FC Dallas' },
    { n: 11, p: 'FW', nm: 'Ruben Providence', c: 'Almere City FC' },
    { n: 7, p: 'FW', nm: 'Josué Casimir', c: 'AJ Auxerre' },
    { n: 20, p: 'FW', nm: 'Duckens Nazon', c: 'Esteghlal FC' },
    { n: 21, p: 'FW', nm: 'Frantzdy Pierrot', c: 'Çaykur Rizespor' },
    { n: 25, p: 'FW', nm: 'Yassin Fortuné', c: 'FC Vizela' },
    { n: 26, p: 'FW', nm: 'Lenny Joseph', c: 'Ferencváros TC' }
  ],
  Croatia: [
    { n: 1, p: 'GK', nm: 'Dominik Livaković', c: 'Fenerbahçe' },
    { n: 23, p: 'GK', nm: 'Dominik Kotarski', c: 'Club Brugge' },
    { n: 12, p: 'GK', nm: 'Ivor Pandur', c: 'Lille' },
    { n: 3, p: 'DF', nm: 'Joško Gvardiol', c: 'Manchester City' },
    { n: 5, p: 'DF', nm: 'Duje Ćaleta-Car', c: 'Southampton' },
    { n: 6, p: 'DF', nm: 'Josip Šutalo', c: 'AFC Ajax' },
    { n: 2, p: 'DF', nm: 'Josip Stanišić', c: 'Bayer Leverkusen' },
    { n: 22, p: 'DF', nm: 'Marin Pongračić', c: 'Fiorentina' },
    { n: 4, p: 'DF', nm: 'Martin Erlić', c: 'Inter Milan' },
    { n: 24, p: 'DF', nm: 'Luka Vušković', c: 'Tottenham Hotspur' },
    { n: 10, p: 'MF', nm: 'Luka Modrić', cap: true, c: 'AC Milan' },
    { n: 8, p: 'MF', nm: 'Mateo Kovačić', c: 'Manchester City' },
    { n: 14, p: 'MF', nm: 'Mario Pašalić', c: 'Atalanta' },
    { n: 13, p: 'MF', nm: 'Nikola Vlašić', c: 'Torino' },
    { n: 15, p: 'MF', nm: 'Luka Sučić', c: 'Real Sociedad' },
    { n: 7, p: 'MF', nm: 'Martin Baturina', c: 'Chelsea' },
    { n: 16, p: 'MF', nm: 'Kristijan Jakić', c: 'Eintracht Frankfurt' },
    { n: 17, p: 'MF', nm: 'Petar Sučić', c: 'Red Bull Salzburg' },
    { n: 11, p: 'MF', nm: 'Nikola Moro', c: 'Lazio' },
    { n: 19, p: 'MF', nm: 'Toni Fruk', c: 'NK Varaždin' },
    { n: 18, p: 'FW', nm: 'Ivan Perišić', c: 'PSV Eindhoven' },
    { n: 9, p: 'FW', nm: 'Andrej Kramarić', c: 'TSG Hoffenheim' },
    { n: 20, p: 'FW', nm: 'Ante Budimir', c: 'CA Osasuna' },
    { n: 25, p: 'FW', nm: 'Marco Pašalić', c: 'Atalanta' },
    { n: 21, p: 'FW', nm: 'Petar Musa', c: 'FC Dallas' },
    { n: 26, p: 'FW', nm: 'Igor Matanović', c: 'Eintracht Frankfurt' }
  ],
  'Cape Verde': [
    { n: 1, p: 'GK', nm: 'Vozinha', c: 'GD Chaves' },
    { n: 12, p: 'GK', nm: 'C. J. Dos Santos', c: 'San Diego FC' },
    { n: 23, p: 'GK', nm: 'Márcio Rosa', c: 'PFC Montana' },
    { n: 6, p: 'DF', nm: 'Roberto Lopes', c: 'Shamrock Rovers' },
    { n: 4, p: 'DF', nm: 'Logan Costa', c: 'Villarreal' },
    { n: 24, p: 'DF', nm: 'Joao Paulo', c: 'FCSB' },
    { n: 2, p: 'DF', nm: 'Diney Borges', c: 'Al-Bataeh SCC' },
    { n: 5, p: 'DF', nm: 'Stopira', c: 'SCU Torreense' },
    { n: 13, p: 'DF', nm: 'Steven Moreira', c: 'Columbus Crew' },
    { n: 15, p: 'DF', nm: 'Wagner Pina', c: 'Trabzonspor' },
    { n: 22, p: 'DF', nm: 'Sidny Lopes Cabral', c: 'SL Benfica' },
    { n: 3, p: 'DF', nm: 'Kelvin Pires', c: 'SJK Seinäjoki' },
    { n: 17, p: 'MF', nm: 'Kevin Pina Lenini', c: 'FK Krasnodar' },
    { n: 8, p: 'MF', nm: 'Jamiro Monteiro', cap: true, c: 'PEC Zwolle' },
    { n: 14, p: 'MF', nm: 'Deroy Duarte', c: 'Ludogorets' },
    { n: 18, p: 'MF', nm: 'Laros Duarte', c: 'Puskás Akadémia' },
    { n: 19, p: 'MF', nm: 'Telmo Arcanjo', c: 'Vitória de Guimarães' },
    { n: 20, p: 'MF', nm: 'Yannick Semedo', c: 'SC Farense' },
    { n: 21, p: 'FW', nm: 'Ryan Mendes', c: 'Igdir FK' },
    { n: 7, p: 'FW', nm: 'Garry Rodrigues', c: 'Apollon Limassol' },
    { n: 25, p: 'FW', nm: 'Willy Semedo', c: 'Omonia Nicosia' },
    { n: 11, p: 'FW', nm: 'Jovane Cabral', c: 'Estrela da Amadora' },
    { n: 16, p: 'FW', nm: 'Benchimol', c: 'Akron Tolyatti' },
    { n: 26, p: 'FW', nm: 'Hélio Varela', c: 'Maccabi Tel-Aviv' },
    { n: 10, p: 'FW', nm: 'Nuno Da Costa', c: 'İstanbul Başakşehir' },
    { n: 9, p: 'FW', nm: 'Dailon Livramento', c: 'Casa Pia AC' }
  ],
  'Congo DR': [
    { n: 1, p: 'GK', nm: 'Lionel Mpasi', c: 'AC Le Havre' },
    { n: 23, p: 'GK', nm: 'Timothy Fayulu', c: 'FC Noah' },
    { n: 12, p: 'GK', nm: 'Mattieu Epolo', c: 'Standard Liège' },
    { n: 5, p: 'DF', nm: 'Chancel Mbemba', c: 'LOSC Lille' },
    { n: 22, p: 'DF', nm: 'Axel Tuanzebe', c: 'Burnley FC' },
    { n: 6, p: 'DF', nm: 'Rocky Bushiri', c: 'Hibernian FC' },
    { n: 4, p: 'DF', nm: 'Steve Kapuadi', c: 'Widzew Łódź' },
    { n: 15, p: 'DF', nm: 'Dylan Batubinsika', c: 'AEL Larissa' },
    { n: 2, p: 'DF', nm: 'Aaron Wan-Bissaka', c: 'West Ham United' },
    { n: 13, p: 'DF', nm: 'Gédéon Kalulu', c: 'Aris Limassol' },
    { n: 3, p: 'DF', nm: 'Arthur Masuaku', c: 'RC Lens' },
    { n: 24, p: 'DF', nm: 'Joris Kayembe', c: 'RKC Genk' },
    { n: 17, p: 'MF', nm: 'Noah Sadiki', c: 'Sunderland AFC' },
    { n: 16, p: 'MF', nm: 'Charles Pickel', c: 'RCD Espanyol' },
    { n: 8, p: 'MF', nm: 'Samuel Moutussamy', c: 'Atromitos FC' },
    { n: 14, p: 'MF', nm: "Ngal'Ayel Mukau", c: 'LOSC Lille' },
    { n: 18, p: 'MF', nm: 'Edo Kayembe', c: 'Watford FC' },
    { n: 19, p: 'MF', nm: 'Nathanaël Mbuku', c: 'Montpellier HSC' },
    { n: 25, p: 'MF', nm: 'Brian Cipenga', c: 'CD Castellón' },
    { n: 10, p: 'MF', nm: 'Gaël Kakuta', c: 'AEL Limassol' },
    { n: 26, p: 'MF', nm: 'Meschack Elía', c: 'Alanyaspor' },
    { n: 11, p: 'MF', nm: 'Théo Bongonda', c: 'Spartak Moscow' },
    { n: 9, p: 'FW', nm: 'Cédric Bakambu', cap: true, c: 'Real Betis' },
    { n: 7, p: 'FW', nm: 'Yoane Wissa', c: 'Newcastle United' },
    { n: 21, p: 'FW', nm: 'Fiston Kalala Mayele', c: 'Pyramids FC' },
    { n: 20, p: 'FW', nm: 'Simon Banza', c: 'Al-Jazira Club' }
  ],
  'Curaçao': [
    { n: 1, p: 'GK', nm: 'Tyrick Bodak', c: 'SV Meppen' },
    { n: 23, p: 'GK', nm: 'Trevor Doornbusch', c: 'FC Groningen' },
    { n: 12, p: 'GK', nm: 'Eloy Room', c: 'Columbus Crew' },
    { n: 2, p: 'DF', nm: 'Riechedly Bazoer', c: 'SC Heerenveen' },
    { n: 13, p: 'DF', nm: 'Joshua Brenet', c: 'FC Twente' },
    { n: 3, p: 'DF', nm: 'Roshon Van Eijma', c: 'RKC Waalwijk' },
    { n: 4, p: 'DF', nm: 'Sherel Floranus', c: 'FC Dallas' },
    { n: 5, p: 'DF', nm: 'Deveron Fonville', c: 'DC United' },
    { n: 6, p: 'DF', nm: 'Juriën Gaari', c: 'ADO Den Haag' },
    { n: 22, p: 'DF', nm: 'Armando Obispo', c: 'Portsmouth' },
    { n: 24, p: 'DF', nm: 'Shurandy Sambo', c: 'FC Groningen' },
    { n: 8, p: 'MF', nm: 'Juninho Bacuna', c: 'FC Volendam' },
    { n: 14, p: 'MF', nm: 'Leandro Bacuna', c: 'Cardiff City' },
    { n: 16, p: 'MF', nm: 'Livano Comenencia', c: 'FC Twente' },
    { n: 17, p: 'MF', nm: 'Kevin Felida', c: 'Beerschot' },
    { n: 15, p: 'MF', nm: "Ar'Jany Martha", c: 'Rotherham United' },
    { n: 18, p: 'MF', nm: 'Tyrese Noslin', c: 'Telstar' },
    { n: 19, p: 'MF', nm: 'Godfried Roemeratoe', c: 'Jong Ajax' },
    { n: 20, p: 'FW', nm: 'Jeremy Antonisse', c: 'Willem II' },
    { n: 11, p: 'FW', nm: 'Tahith Chong', c: 'Sheffield United' },
    { n: 25, p: 'FW', nm: 'Kenji Gorré', c: 'Beerschot' },
    { n: 9, p: 'FW', nm: 'Sontje Hansen', c: 'NEC Nijmegen' },
    { n: 7, p: 'FW', nm: 'Gervane Kastaneer', c: 'SC Heerenveen' },
    { n: 21, p: 'FW', nm: 'Brandley Kuwas', c: 'Sparta Rotterdam' },
    { n: 10, p: 'FW', nm: 'Jürgen Locadia', cap: true, c: 'Philadelphia Union' },
    { n: 26, p: 'FW', nm: 'Jearl Margaritha', c: 'Willem II' }
  ],
  Portugal: [
    { n: 1, p: 'GK', nm: 'Diogo Costa', c: 'Porto' },
    { n: 12, p: 'GK', nm: 'José Sá', c: 'Wolverhampton Wanderers' },
    { n: 22, p: 'GK', nm: 'Rui Silva', c: 'Sporting CP' },
    { n: 23, p: 'GK', nm: 'Ricardo Velho', c: 'Gençlerbirliği' },
    { n: 18, p: 'DF', nm: 'Matheus Nunes', c: 'Manchester City' },
    { n: 2, p: 'DF', nm: 'Diogo Dalot', c: 'Manchester United' },
    { n: 20, p: 'DF', nm: 'Nélson Semedo', c: 'Fenerbahçe' },
    { n: 5, p: 'DF', nm: 'João Cancelo', c: 'Barcelona' },
    { n: 3, p: 'DF', nm: 'Rúben Dias', c: 'Manchester City' },
    { n: 14, p: 'DF', nm: 'Gonçalo Inácio', c: 'Sporting CP' },
    { n: 24, p: 'DF', nm: 'Tomás Araújo', c: 'Benfica' },
    { n: 6, p: 'DF', nm: 'Renato Veiga', c: 'Villarreal' },
    { n: 25, p: 'DF', nm: 'Nuno Mendes', c: 'PSG' },
    { n: 13, p: 'MF', nm: 'Samú Costa', c: 'Mallorca' },
    { n: 15, p: 'MF', nm: 'Rúben Neves', c: 'Al-Hilal' },
    { n: 16, p: 'MF', nm: 'Vitinha', c: 'PSG' },
    { n: 8, p: 'MF', nm: 'João Neves', c: 'PSG' },
    { n: 17, p: 'MF', nm: 'Bruno Fernandes', cap: true, c: 'Manchester United' },
    { n: 10, p: 'MF', nm: 'Bernardo Silva', c: 'Manchester City' },
    { n: 26, p: 'FW', nm: 'Rafael Leão', c: 'AC Milan' },
    { n: 4, p: 'FW', nm: 'Francisco Conceição', c: 'Juventus' },
    { n: 9, p: 'FW', nm: 'Pedro Neto', c: 'Chelsea' },
    { n: 19, p: 'FW', nm: 'Francisco Trincão', c: 'Sporting CP' },
    { n: 11, p: 'FW', nm: 'João Félix', c: 'Al-Nassr' },
    { n: 21, p: 'FW', nm: 'Gonçalo Guedes', c: 'Real Sociedad' },
    { n: 27, p: 'FW', nm: 'Gonçalo Ramos', c: 'PSG' },
    { n: 7, p: 'FW', nm: 'Cristiano Ronaldo', c: 'Al-Nassr' }
  ],
  Austria: [
    { n: 1, p: 'GK', nm: 'Alexander Schlager', c: 'RB Salzburg' },
    { n: 23, p: 'GK', nm: 'Patrick Pentz', c: 'Brondby IF' },
    { n: 12, p: 'GK', nm: 'Florian Wiegele', c: 'FC Viktoria Plzeň' },
    { n: 5, p: 'DF', nm: 'David Alaba', c: 'Real Madrid' },
    { n: 4, p: 'DF', nm: 'Kevin Danso', c: 'Tottenham Hotspur' },
    { n: 13, p: 'DF', nm: 'Stefan Posch', c: '1. FSV Mainz 05' },
    { n: 15, p: 'DF', nm: 'Philipp Lienhart', c: 'SC Freiburg' },
    { n: 22, p: 'DF', nm: 'Phillipp Mwene', c: '1. FSV Mainz 05' },
    { n: 24, p: 'DF', nm: 'Alexander Prass', c: 'TSG 1899 Hoffenheim' },
    { n: 3, p: 'DF', nm: 'Marco Friedl', c: 'Werder Bremen' },
    { n: 6, p: 'DF', nm: 'Michael Svoboda', c: 'Venezia FC' },
    { n: 2, p: 'DF', nm: 'David Affengruber', c: 'Elche CF' },
    { n: 18, p: 'MF', nm: 'Xaver Schlager', c: 'RB Leipzig' },
    { n: 26, p: 'MF', nm: 'Nicolas Seiwald', c: 'RB Leipzig' },
    { n: 16, p: 'MF', nm: 'Marcel Sabitzer', c: 'Borussia Dortmund' },
    { n: 8, p: 'MF', nm: 'Florian Grillitsch', c: 'SC Braga' },
    { n: 19, p: 'MF', nm: 'Carney Chukwuemeka', c: 'Borussia Dortmund' },
    { n: 20, p: 'MF', nm: 'Romando Schmid', c: 'Werder Bremen' },
    { n: 14, p: 'MF', nm: 'Christoph Baumgartner', c: 'RB Leipzig' },
    { n: 17, p: 'MF', nm: 'Konrad Laimer', c: 'Bayern Munich' },
    { n: 7, p: 'MF', nm: 'Patrick Wimmer', c: 'VfL Wolfsburg' },
    { n: 11, p: 'MF', nm: 'Paul Wanner', c: 'PSV Eindhoven' },
    { n: 25, p: 'MF', nm: 'Alessandro Schöpf', c: 'Wolfsberger AC' },
    { n: 9, p: 'FW', nm: 'Marko Arnautovic', cap: true, c: 'Crvena Zvezda' },
    { n: 10, p: 'FW', nm: 'Michael Gregoritsch', c: 'FC Augsburg' },
    { n: 21, p: 'FW', nm: 'Sasa Kalajdzic', c: 'LASK Linz' }
  ],
  Scotland: [
    { n: 1, p: 'GK', nm: 'Craig Gordon', c: 'Heart of Midlothian' },
    { n: 23, p: 'GK', nm: 'Angus Gunn', c: 'Nottingham Forest' },
    { n: 12, p: 'GK', nm: 'Liam Kelly', c: 'Rangers FC' },
    { n: 26, p: 'DF', nm: 'Andy Robertson', cap: true, c: 'Liverpool FC' },
    { n: 5, p: 'DF', nm: 'Grant Hanley', c: 'Hibernian FC' },
    { n: 14, p: 'DF', nm: 'Kieran Tierney', c: 'Celtic FC' },
    { n: 16, p: 'DF', nm: 'Scott McKenna', c: 'Dinamo Zagreb' },
    { n: 6, p: 'DF', nm: 'Jack Hendry', c: 'Al-Ettifaq FC' },
    { n: 2, p: 'DF', nm: 'Nathan Patterson', c: 'Everton FC' },
    { n: 22, p: 'DF', nm: 'Anthony Ralston', c: 'Celtic FC' },
    { n: 4, p: 'DF', nm: 'John Souttar', c: 'Rangers FC' },
    { n: 3, p: 'DF', nm: 'Aaron Hickey', c: 'Brentford FC' },
    { n: 15, p: 'DF', nm: 'Dominic Hyam', c: 'AFC Wrexham' },
    { n: 7, p: 'MF', nm: 'John McGinn', c: 'Aston Villa' },
    { n: 10, p: 'MF', nm: 'Scott McTominay', c: 'SSC Napoli' },
    { n: 11, p: 'MF', nm: 'Ryan Christie', c: 'AFC Bournemouth' },
    { n: 18, p: 'MF', nm: 'Kenny McLean', c: 'Norwich City' },
    { n: 8, p: 'MF', nm: 'Billy Gilmour', c: 'SSC Napoli' },
    { n: 13, p: 'MF', nm: 'Lewis Ferguson', c: 'Bologna FC 1909' },
    { n: 19, p: 'MF', nm: 'Benn Gannon-Doak', c: 'AFC Bournemouth' },
    { n: 17, p: 'MF', nm: 'Findlay Curtis', c: 'Kilmarnock FC' },
    { n: 20, p: 'FW', nm: 'Lyndon Dykes', c: 'Charlton Athletic' },
    { n: 9, p: 'FW', nm: 'Ché Adams', c: 'Torino FC' },
    { n: 25, p: 'FW', nm: 'Lawrence Shankland', c: 'Heart of Midlothian' },
    { n: 24, p: 'FW', nm: 'George Hirst', c: 'Ipswich Town' },
    { n: 21, p: 'FW', nm: 'Ross Stewart', c: 'Southampton FC' }
  ],
  Germany: [
    { n: 1, p: 'GK', nm: 'Oliver Baumann', c: 'Hoffenheim' },
    { n: 12, p: 'GK', nm: 'Manuel Neuer', cap: true, c: 'Bayern Munich' },
    { n: 23, p: 'GK', nm: 'Alexander Nübel', c: 'VfB Stuttgart' },
    { n: 2, p: 'DF', nm: 'Waldemar Anton', c: 'Borussia Dortmund' },
    { n: 3, p: 'DF', nm: 'Nathaniel Brown', c: 'Eintracht Frankfurt' },
    { n: 4, p: 'DF', nm: 'Pascal Groß', c: 'Brighton' },
    { n: 5, p: 'DF', nm: 'Joshua Kimmich', c: 'Bayern Munich' },
    { n: 6, p: 'DF', nm: 'David Raum', c: 'RB Leipzig' },
    { n: 13, p: 'DF', nm: 'Antonio Rüdiger', c: 'Real Madrid' },
    { n: 14, p: 'DF', nm: 'Nico Schlotterbeck', c: 'Borussia Dortmund' },
    { n: 15, p: 'DF', nm: 'Jonathan Tah', c: 'Bayern Munich' },
    { n: 16, p: 'DF', nm: 'Malick Thiaw', c: 'Newcastle United' },
    { n: 7, p: 'MF', nm: 'Leon Goretzka', c: 'Bayern Munich' },
    { n: 8, p: 'MF', nm: 'Jamie Leweling', c: 'VfB Stuttgart' },
    { n: 17, p: 'MF', nm: 'Felix Nmecha', c: 'Borussia Dortmund' },
    { n: 18, p: 'MF', nm: 'Aleksandar Pavlović', c: 'Bayern Munich' },
    { n: 19, p: 'MF', nm: 'Angelo Stiller', c: 'VfB Stuttgart' },
    { n: 20, p: 'MF', nm: 'Florian Wirtz', c: 'Liverpool' },
    { n: 21, p: 'MF', nm: 'Nadiem Amiri', c: 'Mainz' },
    { n: 9, p: 'FW', nm: 'Maximilian Beier', c: 'Borussia Dortmund' },
    { n: 10, p: 'FW', nm: 'Lennart Karl', c: 'Bayern Munich' },
    { n: 11, p: 'FW', nm: 'Kai Havertz', c: 'Arsenal' },
    { n: 22, p: 'FW', nm: 'Deniz Undav', c: 'VfB Stuttgart' },
    { n: 24, p: 'FW', nm: 'Nick Woltemade', c: 'Newcastle United' },
    { n: 25, p: 'FW', nm: 'Leroy Sané', c: 'Galatasaray' },
    { n: 26, p: 'FW', nm: 'Jamal Musiala', c: 'Bayern Munich' }
  ],
  Senegal: [
    { n: 1, p: 'GK', nm: 'Édouard Mendy', c: 'Al-Ahli FC' },
    { n: 12, p: 'GK', nm: 'Yehvann Diouf', c: 'OGC Nice' },
    { n: 23, p: 'GK', nm: 'Mory Diaw', c: 'Le Havre' },
    { n: 2, p: 'DF', nm: 'Kalidou Koulibaly', cap: true, c: 'Al-Hilal' },
    { n: 3, p: 'DF', nm: 'Antoine Mendy', c: 'OGC Nice' },
    { n: 4, p: 'DF', nm: 'Abdoulaye Seck', c: 'Maccabi Haifa' },
    { n: 5, p: 'DF', nm: 'Ismail Jakobs', c: 'Galatasaray' },
    { n: 6, p: 'DF', nm: 'Moussa Niakhaté', c: 'Olympique Lyonnais' },
    { n: 13, p: 'DF', nm: 'Krépin Diatta', c: 'AS Monaco' },
    { n: 14, p: 'DF', nm: 'Ilay Camara', c: 'Anderlecht' },
    { n: 15, p: 'DF', nm: 'Mamadou Sarr', c: 'Chelsea' },
    { n: 16, p: 'DF', nm: 'El-Hadji Malick Diouf', c: 'Villarreal' },
    { n: 22, p: 'DF', nm: 'Moustapha Mbow', c: 'Paris FC' },
    { n: 7, p: 'MF', nm: 'Idrissa Gana Gueye', c: 'Everton' },
    { n: 8, p: 'MF', nm: 'Habib Diarra', c: 'Sunderland' },
    { n: 17, p: 'MF', nm: 'Pape Matar Sarr', c: 'Tottenham Hotspur' },
    { n: 18, p: 'MF', nm: 'Pape Alassane Gueye', c: 'Villarreal' },
    { n: 19, p: 'MF', nm: 'Lamine Camara', c: 'AS Monaco' },
    { n: 20, p: 'MF', nm: 'Pathé Ciss', c: 'Rayo Vallecano' },
    { n: 21, p: 'MF', nm: 'Bara Ndiaye', c: 'Bayern Munich' },
    { n: 9, p: 'FW', nm: 'Sadio Mané', c: 'Al-Nassr FC' },
    { n: 10, p: 'FW', nm: 'Ismaila Sarr', c: 'Crystal Palace' },
    { n: 11, p: 'FW', nm: 'Iliman Ndiaye', c: 'Everton' },
    { n: 24, p: 'FW', nm: 'Nicolas Jackson', c: 'Chelsea' },
    { n: 25, p: 'FW', nm: 'Assane Diao', c: 'Como' },
    { n: 26, p: 'FW', nm: 'Ibrahim Mbaye', c: 'PSG' },
    { n: 27, p: 'FW', nm: 'Chérif Ndiaye', c: 'Samsunspor' },
    { n: 28, p: 'FW', nm: 'Bamba Dieng', c: 'FC Lorient' }
  ],
  Switzerland: [
    { n: 1, p: 'GK', nm: 'Gregor Kobel', c: 'Borussia Dortmund' },
    { n: 12, p: 'GK', nm: 'Yvon Mvogo', c: 'FC Lorient' },
    { n: 23, p: 'GK', nm: 'Marvin Keller', c: 'BSC Young Boys' },
    { n: 2, p: 'DF', nm: 'Manuel Akanji', c: 'Inter Milan' },
    { n: 3, p: 'DF', nm: 'Aurèle Amenda', c: 'Eintracht Frankfurt' },
    { n: 4, p: 'DF', nm: 'Silvan Widmer', c: '1. FSV Mainz 05' },
    { n: 5, p: 'DF', nm: 'Eray Cömert', c: 'FC Valencia' },
    { n: 6, p: 'DF', nm: 'Nico Elvedi', c: 'Borussia Mönchengladbach' },
    { n: 13, p: 'DF', nm: 'Luca Jaquez', c: 'VfB Stuttgart' },
    { n: 14, p: 'DF', nm: 'Ricardo Rodriguez', c: 'Real Betis' },
    { n: 15, p: 'DF', nm: 'Miro Muheim', c: 'Hamburger SV' },
    { n: 7, p: 'MF', nm: 'Granit Xhaka', cap: true, c: 'Sunderland' },
    { n: 8, p: 'MF', nm: 'Remo Freuler', c: 'FC Bologna' },
    { n: 16, p: 'MF', nm: 'Denis Zakaria', c: 'AS Monaco' },
    { n: 17, p: 'MF', nm: 'Fabian Rieder', c: 'FC Augsburg' },
    { n: 18, p: 'MF', nm: 'Johan Manzambi', c: 'SC Freiburg' },
    { n: 19, p: 'MF', nm: 'Ardon Jashari', c: 'AC Milan' },
    { n: 20, p: 'MF', nm: 'Djibril Sow', c: 'FC Sevilla' },
    { n: 21, p: 'MF', nm: 'Michel Aebischer', c: 'Pisa' },
    { n: 22, p: 'MF', nm: 'Christian Fassnacht', c: 'BSC Young Boys' },
    { n: 9, p: 'FW', nm: 'Breel Embolo', c: 'Stade Rennais' },
    { n: 10, p: 'FW', nm: 'Cedric Itten', c: 'Fortuna Düsseldorf' },
    { n: 11, p: 'FW', nm: 'Zeki Amdouni', c: 'Burnley' },
    { n: 24, p: 'FW', nm: 'Rubén Vargas', c: 'FC Sevilla' },
    { n: 25, p: 'FW', nm: 'Dan Ndoye', c: 'Nottingham Forest' },
    { n: 26, p: 'FW', nm: 'Noah Okafor', c: 'Leeds United' }
  ],
  Norway: [
    { n: 1, p: 'GK', nm: 'Ørjan Nyland', c: 'Sevilla' },
    { n: 12, p: 'GK', nm: 'Sander Tangvik', c: 'Hamburger SV' },
    { n: 23, p: 'GK', nm: 'Egil Selvik', c: 'Watford' },
    { n: 2, p: 'DF', nm: 'Kristoffer Ajer', c: 'Brentford' },
    { n: 3, p: 'DF', nm: 'Leo Østigård', c: 'Genoa' },
    { n: 4, p: 'DF', nm: 'Julian Ryerson', c: 'Borussia Dortmund' },
    { n: 5, p: 'DF', nm: 'David Møller Wolfe', c: 'Wolverhampton Wanderers' },
    { n: 6, p: 'DF', nm: 'Fredrik André Bjørkan', c: 'Bodø/Glimt' },
    { n: 13, p: 'DF', nm: 'Henrik Falchener', c: 'Viking FK' },
    { n: 14, p: 'DF', nm: 'Sondre Langås', c: 'Derby County' },
    { n: 15, p: 'DF', nm: 'Torbjørn Heggem', c: 'Bologna' },
    { n: 16, p: 'DF', nm: 'Marcus Holmgren Pedersen', c: 'Torino' },
    { n: 7, p: 'MF', nm: 'Martin Ødegaard', c: 'Arsenal' },
    { n: 8, p: 'MF', nm: 'Morten Thorsby', c: 'Cremonese' },
    { n: 17, p: 'MF', nm: 'Patrick Berg', c: 'Bodø/Glimt' },
    { n: 18, p: 'MF', nm: 'Sander Berge', c: 'Fulham' },
    { n: 19, p: 'MF', nm: 'Jens Petter Hauge', c: 'Bodø/Glimt' },
    { n: 20, p: 'MF', nm: 'Kristian Thorstvedt', c: 'Sassuolo' },
    { n: 21, p: 'MF', nm: 'Andreas Schjelderup', c: 'Benfica' },
    { n: 22, p: 'MF', nm: 'Fredrik Aursnes', c: 'Benfica' },
    { n: 24, p: 'MF', nm: 'Thelo Aasgaard', c: 'Rangers' },
    { n: 9, p: 'FW', nm: 'Erling Haaland', cap: true, c: 'Manchester City' },
    { n: 10, p: 'FW', nm: 'Jørgen Strand Larsen', c: 'Crystal Palace' },
    { n: 11, p: 'FW', nm: 'Alexander Sørloth', c: 'Atlético Madrid' },
    { n: 25, p: 'FW', nm: 'Antonio Nusa', c: 'RB Leipzig' },
    { n: 26, p: 'FW', nm: 'Oscar Bobb', c: 'Fulham' }
  ],
  'South Korea': [
    { n: 1, p: 'GK', nm: 'Kim Seunggyu', c: 'FC Tokyo' },
    { n: 12, p: 'GK', nm: 'Song Bumkeun', c: 'Jeonbuk Hyundai Motors' },
    { n: 23, p: 'GK', nm: 'Jo Hyeonwoo', c: 'Ulsan HD FC' },
    { n: 2, p: 'DF', nm: 'Kim Minjae', c: 'Bayern Munich' },
    { n: 3, p: 'DF', nm: 'Cho Yumin', c: 'Sharjah FC' },
    { n: 4, p: 'DF', nm: 'Lee Hanbeom', c: 'FC Midtjylland' },
    { n: 5, p: 'DF', nm: 'Kim Taehyeon', c: 'Kashima Antlers' },
    { n: 6, p: 'DF', nm: 'Lee Kihyuk', c: 'Gangwon FC' },
    { n: 13, p: 'DF', nm: 'Lee Taeseok', c: 'Austria Vienna' },
    { n: 14, p: 'DF', nm: 'Seol Youngwoo', c: 'Red Star Belgrade' },
    { n: 15, p: 'DF', nm: 'Kim Moonhwan', c: 'Daejeon Hana Citizen' },
    { n: 7, p: 'MF', nm: 'Hwang Inbeom', c: 'Feyenoord Rotterdam' },
    { n: 8, p: 'MF', nm: 'Park Jinseob', c: 'Zhejiang FC' },
    { n: 16, p: 'MF', nm: 'Jens Castrop', c: 'Borussia Mönchengladbach' },
    { n: 17, p: 'MF', nm: 'Paik Seungho', c: 'Birmingham City' },
    { n: 18, p: 'MF', nm: 'Kim Jingyu', c: 'Jeonbuk Hyundai Motors' },
    { n: 19, p: 'MF', nm: 'Lee Kangin', c: 'Paris Saint-Germain' },
    { n: 20, p: 'MF', nm: 'Bae Junho', c: 'Stoke City' },
    { n: 21, p: 'MF', nm: 'Lee Jaesung', c: '1. FSV Mainz 05' },
    { n: 22, p: 'MF', nm: 'Lee Donggyeong', c: 'Ulsan HD FC' },
    { n: 9, p: 'FW', nm: 'Son Heungmin', cap: true, c: 'Los Angeles FC' },
    { n: 10, p: 'FW', nm: 'Eom Jisung', c: 'Swansea City' },
    { n: 11, p: 'FW', nm: 'Yang Hyunjun', c: 'Celtic FC' },
    { n: 24, p: 'FW', nm: 'Oh Hyeongyu', c: 'Beşiktaş JK' },
    { n: 25, p: 'FW', nm: 'Hwang Heechan', c: 'Wolverhampton Wanderers' },
    { n: 26, p: 'FW', nm: 'Cho Guesung', c: 'FC Midtjylland' }
  ],
  'Türkiye': [
    { n: 1, p: 'GK', nm: 'Altay Bayındır', c: 'Manchester United' },
    { n: 3, p: 'DF', nm: 'Ferdi Kadıoğlu', c: 'Benfica' },
    { n: 8, p: 'MF', nm: 'Orkun Kökçü', c: 'Benfica' },
    { n: 10, p: 'MF', nm: 'Hakan Çalhanoğlu', cap: true, c: 'Inter Milan' },
    { n: 11, p: 'MF', nm: 'Arda Güler', c: 'Real Madrid' },
    { n: 7, p: 'FW', nm: 'Barış Alper Yılmaz', c: 'Galatasaray' },
    { n: 17, p: 'MF', nm: 'Kenan Yıldız', c: 'Juventus' },
    { n: 20, p: 'FW', nm: 'Yunus Akgün', c: 'Galatasaray' }
  ]
};
